/**
 * DMTSP Fabric Migration Accelerators - Main JavaScript
 * Handles UI interactions, accordion functionality, and navigation
 */

/**
 * Toggle accelerator accordion panels
 */
function toggleAccelerator(num) {
    const card = document.getElementById('acc-' + num);
    const isOpen = card.classList.contains('open');

    // Close all other cards
    document.querySelectorAll('.accelerator-card').forEach(c => {
        c.classList.remove('open');
    });

    // Toggle current card
    if (!isOpen) {
        card.classList.add('open');

        // Smooth scroll to card
        setTimeout(() => {
            card.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }, 100);
    }
}

/**
 * Smooth scroll navigation
 */
document.addEventListener('DOMContentLoaded', function() {
    // Smooth scroll for anchor links
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function(e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                const headerOffset = 80;
                const elementPosition = target.getBoundingClientRect().top;
                const offsetPosition = elementPosition + window.pageYOffset - headerOffset;

                window.scrollTo({
                    top: offsetPosition,
                    behavior: 'smooth'
                });
            }
        });
    });

    // Add animation on scroll
    const observerOptions = {
        threshold: 0.1,
        rootMargin: '0px 0px -50px 0px'
    };

    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add('animate-in');
            }
        });
    }, observerOptions);

    // Observe elements for animation
    document.querySelectorAll('.overview-card, .accelerator-card, .summary-card, .result-card').forEach(el => {
        observer.observe(el);
    });

    // Navbar scroll effect
    const navbar = document.querySelector('.navbar');
    let lastScroll = 0;

    window.addEventListener('scroll', () => {
        const currentScroll = window.pageYOffset;

        if (currentScroll > 100) {
            navbar.classList.add('scrolled');
        } else {
            navbar.classList.remove('scrolled');
        }

        lastScroll = currentScroll;
    });

    // Active nav link highlighting
    const sections = document.querySelectorAll('section[id]');
    const navLinks = document.querySelectorAll('.nav-links a');

    window.addEventListener('scroll', () => {
        let current = '';

        sections.forEach(section => {
            const sectionTop = section.offsetTop - 100;
            const sectionHeight = section.offsetHeight;

            if (window.pageYOffset >= sectionTop && window.pageYOffset < sectionTop + sectionHeight) {
                current = section.getAttribute('id');
            }
        });

        navLinks.forEach(link => {
            link.classList.remove('active');
            if (link.getAttribute('href') === '#' + current) {
                link.classList.add('active');
            }
        });
    });

    // Input field formatting
    document.querySelectorAll('.calc-inputs input[type="number"]').forEach(input => {
        input.addEventListener('focus', function() {
            this.select();
        });

        input.addEventListener('change', function() {
            calculateROI();
        });

        input.addEventListener('keyup', debounce(function() {
            calculateROI();
        }, 300));
    });

    // Initialize first accelerator as open
    toggleAccelerator(1);
});

/**
 * Debounce function for input handling
 */
function debounce(func, wait) {
    let timeout;
    return function executedFunction(...args) {
        const later = () => {
            clearTimeout(timeout);
            func(...args);
        };
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
    };
}

/**
 * Print-friendly export
 */
function exportToPDF() {
    window.print();
}

/**
 * Copy results to clipboard
 */
function copyResults() {
    const base = document.getElementById('baseHours').textContent;
    const accelerated = document.getElementById('acceleratedHours').textContent;
    const saved = document.getElementById('savedHours').textContent;
    const cost = document.getElementById('costSavings').textContent;
    const efficiency = document.getElementById('efficiencyValue').textContent;

    const text = `DMTSP Fabric Migration Accelerator Analysis
---------------------------------------
Base Estimate: ${base} hours
With Accelerators: ${accelerated} hours
Hours Saved: ${saved} hours
Cost Savings: ${cost}
Overall Efficiency Gain: ${efficiency}

Generated by DMTSP Accelerator Calculator`;

    navigator.clipboard.writeText(text).then(() => {
        alert('Results copied to clipboard!');
    }).catch(err => {
        console.error('Failed to copy:', err);
    });
}

/**
 * Add keyboard accessibility
 */
document.addEventListener('keydown', function(e) {
    if (e.key === 'Escape') {
        // Close all accordions on Escape
        document.querySelectorAll('.accelerator-card').forEach(c => {
            c.classList.remove('open');
        });
    }
});

// Make functions available globally
window.toggleAccelerator = toggleAccelerator;
window.exportToPDF = exportToPDF;
window.copyResults = copyResults;
